General:                                                                #基础设置
    Prefix:                 '#'                                         #指令前缀，如果接收到的消息带有该前缀将视为一个指令处理
    ErrorGroups:            [284196625]                                 #错误日志群，发生错误时会将日志发送到这个群
    ErrorMsg:               |                                           #处理异常时返回的消息
                            出了点小问题，稍后再试吧
                            [image:C:\BotImg\emmm.jpg]

Permissions:
    AcceptGroups:           [284196625]                                 #白名单，只处理这些群的消息，黑名单和白名单同时为空时则处理所有群消息
    RefuseGroups:           []                                          #黑名单，不处理这些群的消息，黑名单和白名单同时设值时则只有黑名单生效
    SuperManagers:          [1524514426]                                #超级管理员列表,可以使用管理指令
    SetuGroups:             [284196625]                                 #拥有涩图权限的群
    SaucenaoGroups:         [284196625]                                 #拥有以图搜图权限的群
    SubscribeGroups:        [284196625]                                 #拥有订阅权限的群

Repeater:                                                               #复读机
    Enable:                 true                                        #是否启用
    RepeatTime:             3                                           #重复收到N条消息后触发复读功能
    RepeatMode:             0                                           #复读模式，0：简单模式

Welcome:                                                                #入群欢迎
    Enable:                 true                                        #是否启用
    Template:               '欢迎入群！'                                 #默认欢迎模版
    Special:                                                            #为单独的群设定单独的模版
        - GroupId:          284196625                                   #群id(群号)
          Template:         |                                           #群欢迎模版
                            欢迎新厨子
                            [image:C:\BotImg\welcome.png]
                            略略略

Reminder:                                                               #定时消息
    Enable:                 true                                        #是否启用
    Timers:                                                             #定时列表
        - Cron:             '0 0 18 ? * WED,SUN'                        #cron表达式
          Name:             '深渊结算提醒'                               #定时器名称
          Groups:           [284196625]                                 #群号
          AtAll:            false                                       #是否艾特群体
          AtMembers:        []                                          #艾特群员QQ号列表
          Template:         |                                           #消息模版
                            今天是深渊结算的日子，舰长打穿红莲了没？
                            [image:C:\BotImg\welcome.png]

Setu:                                                                   #色图相关
    GroupCD:                5                                           #共享CD(秒)，使用命令后全群需要CD才能重新使用该功能
    MemberCD:               30                                          #独立CD(秒)，单个群员使用命令后需要等待的CD
    NoneCDGroups:           []                                          #0CD群
    NoneCDMembers:          []                                          #0CD群员
    MaxDaily:               0                                           #每人每日最大使用次数,0表示无限制
    ImgSavePath:            'C:\BotImg\DownImg'                         #图片存放目录
    RevokeInterval:         30                                          #N秒后撤回,0表示不撤回
    Lolicon:                                                            #Lolicon图床https://api.lolicon.app/#/setu
        Enable:             true                                        #是否启用
        Command:            '瑟图'                                      #命令，用法：#瑟图合法萝莉
        DisableMsg:         '不可以色色！'                               #功能未启用时返回的消息
        ErrorMsg:           '申请色色失败！请重新尝试'                   #发生错误时返回的消息
        CustomEnable:       true                                        #是否允许查找自定义涩图，如:#涩图可可萝
        CustomDisableMsg:   '自定义功能已关闭！'                         #禁用自定义时返回的消息
        ProcessingMag:      '正在使用色图探测器探测你要的色图...'         #开始查找前返回的消息
        Template:           ''
    Pixiv:                                                              #Pixiv图床https://www.pixiv.net
        Enable:             true                                        #是否启用
        Command:            '涩图'                                      #命令，用法：#涩图 或 #涩图可可萝
        DisableMsg:         '不可以色色！'                               #功能未启用时返回的消息
        NotFoundMsg:        '色图探测器毫无反应，找不到你要的色图'        #找不到相应色图时返回的消息
        ErrorMsg:           '申请色色失败！请重新尝试'                    #发生错误时返回的消息
        DownErrorImg:       '[image:C:\BotImg\downError.png]'           #图片下载失败是的替代图片
        DownWithPixivCat:   false                                       #通过pixiv.cat代理下载图片
        CustomEnable:       true                                        #是否允许查找自定义涩图，如:#涩图可可萝，值为false将根据 RandomMode 中的设定查找图片
        CustomDisableMsg:   '自定义功能已关闭！'                         #禁用自定义时返回的消息
        RandomMode:         2                                           #1：随机一个RandomTags中标签进行搜索，2：随机获取一个已订阅画师的作品
        RandomTags:         ['德丽莎','テレサ・アポカリプス']              #没有指定标签时随机获取的标签
        ProcessingMsg:      '正在使用色图探测器探测你要的色图...'           #开始查找前返回的消息
        Template:           ''
        MinBookmark:        800                                         #最低收藏数，用于判断涩图是否合格(标签搜索时试用)
        MinBookRate:        0.05                                        #最低收藏率，收藏数/浏览数(标签搜索时试用)
        CookieExpire:       1296000                                     #cookie失效时间(秒)，超过该天数后需要使用命令更新cookie，建议cookie每15天更新一次
        CookieExpireMsg:    'emmmm,cookie过期了,请艾特管理员更新cookie[image:C:\BotImg\welcome.png]'   #cookie过期时返回的消息
                            
Saucenao:                                                                  #Saucenao以图搜图，查找原图功能
    Enable:                 true                                            #是否启用
    Command:                '原图'                                          #命令，用法：#原图 或 原图+图片
    DisableMsg:             '没有，快爬！'                                  #功能未启用时返回的消息
    NotFoundMsg:            '色图探测器毫无反应，找不到你想要的色图'          #找不到相应色图时返回的消息
    ErrorMsg:               '申请色色失败！请重新尝试'                       #发生错误时返回的消息
    DownErrorImg:           '[image:C:\BotImg\downError.png]'              #图片下载失败是的替代图片
    ProcessingMag:          '正在使用色图探测器探测你要的色图...'            #开始查找前返回的消息
    Template:               ''
    GroupCD:                0                                              #共享CD(秒)，使用命令后全群需要CD才能重新使用该功能
    MemberCD:               0                                              #独立CD(秒)，单个群员使用命令后需要等待的CD
    MaxDaily:               0                                              #每人每日最大使用次数,0表示无限制
    WaitSeconds:            60                                             #等待图片的时长(秒)
    MaxReceive:             0                                              #每次最多接收并查询多少张图片，用户发送的图片数量超出该值时只处理前N张图片

Subscribe:                                                              #订阅相关
    PixivUser:                                                          #p站用户
        Enable:             true                                        #是否启用
        AddCommand:         '订阅画师'                                   #订阅命令,需要管理员执行
        RmCommand:          '退订画师'                                   #退订命令,需要管理员执行
        Template:           ''
        DownErrorImg:       '[image:C:\BotImg\downError.png]'           #图片下载失败是的替代图片
        ScanInterval:       3600                                        #扫描间隔(秒)
        ShelfLife:          43200                                       #保质期(秒),超过保质期将不会推送,0表示永不过期
    PixivTag:                                                           #p站标签
        Enable:             true                                        #是否启用
        AddCommand:         '订阅标签'                                   #订阅命令,需要管理员执行
        RmCommand:          '退订标签'                                   #退订命令,需要管理员执行
        Template:           ''
        DownErrorImg:       '[image:C:\BotImg\downError.png]'           #图片下载失败是的替代图片
        ScanInterval:       1800                                        #扫描间隔(秒)
    BiliUp:                                                             #b站up主
        Enable:             true                                        #是否启用
        AddCommand:         '订阅up'                                    #订阅命令,需要管理员执行
        RmCommand:          '退订up'                                    #退订命令,需要管理员执行
        Template:           ''
        ScanInterval:       60                                          #扫描间隔(秒)
    BiliLive:                                                           #b站直播
        Enable:             true                                        #是否启用
        AddCommand:         '订阅直播'                                   #订阅命令,需要管理员执行
        RmCommand:          '退订直播'                                   #退订命令,需要管理员执行
        Template:           ''
        ScanInterval:       60                                          #扫描间隔(秒)
    Mihoyo:                                                             #米游戏社版主
        Enable:             true                                        #是否启用
        AddCommand:         '订阅版主'                                   #订阅命令,需要管理员执行
        RmCommand:          '退订版主'                                   #退订命令,需要管理员执行
        Template:           ''
        ScanInterval:       60                                          #扫描间隔(秒)
