General:                                                      #基础设置
    Prefix:             '#'                                   #指令前缀，如果接收到的消息带有该前缀将视为一个指令处理
    AcceptGroups:       [284196625]                           #白名单，只处理这些群的消息，黑名单和白名单同时为空时则处理所有群消息
    RefuseGroups:       []                                    #黑名单，不处理这些群的消息，黑名单和白名单同时设值时则只有黑名单生效
    ErrorGroups:        [284196625]                           #错误日志群，发生错误时会将日志发送到这个群
    SuperManagers:      [1524514426]                          #超级管理员列表,可以使用管理指令
Repeater:                                                     #复读机
    Enable:             true                                  #是否启用
    RepeatTime:         3                                     #重复收到N条消息后触发复读功能
    RepeatMode:         0                                     #复读模式，0：简单模式
Welcome:                                                      #入群欢迎
    Enable:             true                                  #是否启用
    Template:           '欢迎入群！'                           #默认欢迎模版
    Special:                                                  #为单独的群设定单独的模版
        - GroupId:      284196625                             #群id(群号)
          Template:     |                                     #群欢迎模版
                        欢迎新厨子
                        [image:C:\123.jpg]
                        略略略
Reminder:                                                     #定时消息
    Enable:             true                                  #是否启用
    Timers:                                                   #定时列表
        - Cron:         '0 0 0/1 * * ?'                       #cron表达式
          AtAll:        false                                 #是否艾特群体
          AtMembers:    [1524514426]                          #艾特群员列表
          Template:     '整点报时!'                            #消息模版
        - Cron:         '0 0 18 ? * WED,SUN'
          AtAll:        true                                  
          AtMembers:    []
          Template:     '今晚深渊结算！'