Enable:                          true                                           #是否启用
JoinCommands:                   ['加入游戏']                                    #加入游戏命令
StartCommands:                  ['开始游戏']                                    #跳过玩家等待流程，强制开始游戏命令
StopCommands:                   ['结束游戏']                                    #强制结束游戏命令
Undercover:                                                                     #谁是卧底
    Enable:                     true                                            #是否启用
    CreateCommands:             ['谁是卧底','卧底']                             #创建游戏命令
    AddWordCommands:            ['添加词条','新增词条']                         #新增词条命令，需要私聊使用
    SendWordCommands:           ['我的词条']                                    #游戏中获取词条命令
    AddWordLimits:              10                                              #非管理员限制添加的未审核词条数量，0表示不允许添加
    SendIdentity:               false                                           #私聊发送词条的同时告知玩家身份
    PrivateVote:                false                                           #仅允许私聊投票，否则同时允许群聊和私聊投票
    FirstRoundNonVoting:        3                                               #当玩家人数小于等于该数量时，首轮不出现投票环节
    MaxSimilarity:              60                                              #与历史发言的最高相似度(%)
    MatchSeconds:               60                                              #等待玩家加入的时间(秒)
    PrepareSeconds:             10                                              #派发词条后进入发言环节前的准备时间(秒)
    SpeakingSeconds:            120                                             #每个玩家的发言时长(秒)
    VotingSeconds:              120                                             #投票环节时长(秒)
    FailedMuteSeconds:          0                                               #失败方被禁言的时长(秒)
    ViolatedMuteSeconds:        0                                               #违规玩家被禁言的时长(秒)
    RuleMsg:                    |
                                以下是游戏规则：
                                平民：找出混在其中的所有的卧底和白板
                                卧底：隐藏自己，直到所有平民出局，或者存活至仅剩2人为止
                                白板：没有词条，根据其他玩家的发言推测词条，找出卧底或者存活到仅剩2人为止，白板不会出现在前两名发言玩家当中
                                词条：除了白板以外，其他玩家的发言中不允许出现词条本身，否则游戏自动结束。当白板的发言内容中包含任意一个词条时，白板获胜