Enable:                     false                                               #是否启用
Timers:                                                                         #定时列表
    - Enable:               true                                                #定时器开关
      Cron:                 '0 0 18 ? * WED,SUN'                                #cron表达式(需要自行百度cron格式)
      Name:                 '深渊结算提醒'                                      #定时器名称(仅用于控制台显示)
      Groups:               [284196392]                                         #群号
      AtAll:                false                                               #是否艾特全体
      AtMembers:            []                                                  #艾特群员QQ号列表
      Templates:                                                                #消息模版
          - Template:       |                                              
                            今天是深渊结算的日子，旅行者打穿红莲了没？
                            [image:BotImg/face/shenyuanjiesuan.png]