Enable:                     true                                                #是否启用
Commands:                   ['原图','搜图','saucenao']                          #命令
NotFoundMsg:                '找不到相似的图，换一张完整的图片试试吧~'           #找不到相应原图时返回的消息
ProcessingMsg:              '正在通过saucenao尝试搜索原图...'                   #开始查找前返回的消息
Template:                   '共找到 {MatchCount} 条匹配信息，今天剩余使用次数{TodayLeft}次，本消息将在{RevokeInterval}秒后撤回，CD{MemberCD}秒'
MemberCD:                   30                                                  #独立CD(秒)，单个群员使用命令后需要等待的CD
MaxDaily:                   0                                                   #每人每日最大使用次数，0表示无限制
MaxReceive:                 10                                                  #每次最多接收并查询多少张图片，0表示无限制
MinSimilarity:              60                                                  #最低相似度，范围0~100(%)
SaucenaoReadCount:          3                                                   #最多展示前N个Saucenao中的匹配结果
PixivPriority:              80                                                  #优先返回相似度高于该值的Pixiv中的结果，范围0~100(%)
SinglePriority:             85                                                  #相似度高于该值时，只返回第一个匹配度最高的结果，范围0~100(%)
ImagePriority:              80                                                  #相似度高于该值时，才显示图片，范围0~100(%)
PullOrigin:                 true                                                #尝试从源网站中获取图片和详细信息
SendPrivate:                true                                                #同时私聊发送结果
RevokeInterval:             0                                                   #N秒后撤回，0表示不撤回
RevokeSearched:             false                                               #是否撤回被查找的图片
ContinueAscii2d:            true                                                #Saucenao没有匹配结果时是否继续使用Ascii2d搜索，true：是，false：否
Ascii2dWithIp:              false                                               #使用IP请求Ascii2d，遇到403等错误时可以尝试将该值改为true
Ascii2dReadCount:           3                                                   #从Ascii2d的搜索结果中读取前N条，0表示无限制