General:                                                                            #基础设置
    Prefix:                     '#'                                                 #指令前缀，如果接收到的消息带有该前缀将视为一个指令处理
    DownloadPath:               'C:\BotImg\download'                                #下载文件(比如p站图片等)存放目录
    DownErrorImgPath:           'C:\BotImg\face\downError.png'                     #图片下载失败时的替代图片
    ErrorGroups:                [284196392]                                         #错误日志群，发生错误时会将日志发送到这些群
    ErrorMsg:                   |                                                   #处理异常时返回的消息
                                出了点小问题，稍后再试吧
                                [image:C:\BotImg\face\emmm.jpg]
    DisableMsg:                 '该功能未开启'                                      #功能未启用时返回的消息
    NoPermissionsMsg:           '该功能未授权'                                      #功能未授权时返回的消息
    ManagersRequiredMsg:        '该功能需要管理员执行'                              #需要管理员权限时返回的消息
    SetuCustomDisableMsg:       '自定义功能已关闭'                                  #禁用自定义时返回的消息

Pixiv:
    FreeProxy:                  false                                               #开启pixiv免代理模式，推荐有vpn的情况下禁用，启用后将使用{ImgProxy}下载图片
    HttpProxy:                  ''                                                  #pixiv代理地址，值为空表示直连，FreeProxy启用后失效，格式：http://127.0.0.1:7890
    ImgProxy:                   ''                                                  #图片代理地址，值为空表示不使用代理，FreeProxy启用后使用该值下载图片，默认：https://i.pixiv.re
    ImgShowMaximum:             1                                                   #同一个作品最多显示N张图片，0表示无限制
    TagShowMaximum:             5                                                   #同一个作品最多显示N个标签，0表示无限制
    UrlShowMaximum:             3                                                   #同一个作品最多显示N条原图链接，0表示无限制
    ImgSize:                    'thumb'                                             #发送色图的尺寸：thumb，small，regular，original。默认为thumb，推荐使用thumb或small降低触发风控的概率
    OriginUrlProxy:             'https://i.pixiv.re'                                #pixiv原图链接的代理地址，如果QQ中打开原图链接时如果显示已停止访问，可以修改该值到其他图片代理地址，默认：https://i.pixiv.re(有频率限制)，也可以参照 https://github.com/GardenHamster/Theresa3rd-Bot/blob/main/pixivproxy.md 搭建自己的代理地址
    SendImgBehind:              false                                               #将涩图信息和图片分开发送，先发送作品信息，后发送图片，可以开启此项避免消息被吞
    ImgRetryTimes:              1                                                   #图片下载失败后重试次数，0表示不重试
    ErrRetryTimes:              1                                                   #读取作品失败后的重试次数，0表示不重试
    CookieExpire:               5184000                                             #cookie失效时间(秒)，超过该时间后需要使用命令更新cookie，建议cookie每60天更新一次
    CookieExpireMsg:            'emmmm,cookie过期了,请艾特管理员更新cookie'         #cookie过期时返回的消息
    Template:                   |                                                   #pixiv模版，值为空时将使用默认模版
                                PixivId：{PixivId}，标题：{IllustTitle}，画师：{UserName}，画师id：{UserId}，
                                收藏：{BookmarkCount}，赞：{LikeCount}，浏览：{ViewCount}，
                                耗时：{CostSecond}s，标签图片：{RelevantCount}张，作品图片:{PageCount}张
                                标签：{Tags}，点击下方链接可以查看原图
                                {Urls}

Permissions:                                                                        #权限设置
    SuperManagers:              [123456789]                                         #超级管理员列表,可以使用管理指令
    LimitlessMembers:           [123456789]                                         #功能冷却时间和每日次数无限制的成员
    AcceptGroups:               [284196392,123456789]                               #白名单，只处理这些群的消息
    SetuGroups:                 [284196392]                                         #拥有涩图权限的群
    SetuShowImgGroups:          [284196392]                                         #允许发送图片的群，否则只发送图片链接
    SetuShowAIGroups:           [284196392]                                         #允许发送AI图片的群
    SetuShowR18Groups:          []                                                  #允许出现r18内容的群，图片将使用链接代替
    SetuCustomGroups:           [284196392]                                         #允许查找自定义涩图的群
    SetuNoneCDGroups:           [284196392]                                         #涩图没有CD的群
    SetuLimitlessGroups:        [284196392]                                         #涩图每日次数无限制的群
    SaucenaoGroups:             [284196392]                                         #拥有以图搜图权限的群
    SaucenaoR18Groups:          [284196392]                                         #以图搜图允许发送r18结果的群，图片将使用链接代替
    SubscribeGroups:            [284196392]                                         #拥有订阅权限的群

Manage:                                                                             #管理相关
    PixivCookieCommands:         ['pixivcookie','pck']                              #更新pixiv cookie 指令，需要私聊使用
    SaucenaoCookieCommands:      ['saucenaocookie','sck']                           #更新saucenao cookie 指令，需要私聊使用
    DisableTagCommands:          ['禁止标签','屏蔽标签']                             #禁止一个涩图关键词，禁止后不允许被搜索
    EnableTagCommands:           ['解禁标签','解锁标签']                             #解禁一个涩图关键词
    DisableMemberCommands:       ['禁止成员','拉黑成员']                             #将一个群成员拉入黑名单，所有群生效
    EnableMemberCommands:        ['解禁成员']                                       #将一个群成员从黑名单移除，所有群生效
    
Menu:                                                                               #菜单指令
    Enable:                     true                                                #是否启用
    Commands:                   ['菜单','帮助','功能','指令','命令','help']           #命令
    Template:                   ''                                                  #菜单模版，可自行设定，值为空时将自动生成

Repeater:                                                                           #复读机
    Enable:                     true                                                #是否启用
    RepeatTime:                 3                                                   #重复收到N条消息后触发复读功能
    RepeatMode:                 0                                                   #复读模式，0：简单模式

Welcome:                                                                            #入群欢迎
    Enable:                     true                                                #是否启用
    Template:                   '欢迎入群！'                                        #默认欢迎模版
    Special:                                                                        #为单独的群设定单独的模版
        - GroupId:              284196392                                           #群id(群号)，这里只能填一个
          Template:             |                                                   #群欢迎模版
                                欢迎萌新
                                [image:C:\BotImg\face\welcome.png]
                                请认真阅读群内的相关公告

        - GroupId:              1234567890                                          #群id(群号)
          Template:             '新人爆照!\r\n进群就别想走了哦~'                    #群欢迎模版

Reminder:                                                                           #定时消息
    Enable:                     true                                                #是否启用
    Timers:                                                                         #定时列表
        - Cron:                 '0 0 18 ? * WED,SUN'                                #cron表达式，可以百度cron格式，或者在线生成
          Name:                 '深渊结算提醒'                                      #定时器名称
          Groups:               [284196392]                                         #群号
          AtAll:                false                                               #是否艾特群体
          AtMembers:            []                                                  #艾特群员QQ号列表
          Template:             |                                                   #消息模版
                                今天是深渊结算的日子，旅行者打穿红莲了没？
                                [image:C:\BotImg\face\shenyuanjiesuan.png]

Setu:                                                                               #色图相关
    GroupCD:                    5                                                   #共享CD(秒)，使用命令后全群需要CD才能重新使用该功能
    MemberCD:                   30                                                  #独立CD(秒)，单个群员使用命令后需要等待的CD
    DisableTagsMsg:             '禁止查找这个类型的涩图'                            #标签被禁用时返回的消息
    NotFoundMsg:                '色图探测器毫无反应，找不到你要的色图'              #找不到相应色图时返回的消息
    ProcessingMsg:              '正在使用色图探测器探测你要的色图...'               #开始查找前返回的消息，值为空时不发送
    MaxDaily:                   20                                                  #每人每日最大使用次数，0表示无限制
    RevokeInterval:             0                                                   #N秒后撤回,0表示不撤回
    SendPrivate:                true                                                #同时私聊发送

    Pixiv:                                                                          #Pixiv图床https://www.pixiv.net
        Enable:                 true                                                #是否启用
        Commands:               ['涩图']                                              #命令，用法：#涩图 或 #涩图可可萝
        RandomMode:             1                                                   #没有指定标签时获取图片的模式，1：随机一个RandomTags中标签进行搜索，2：随机获取一个已订阅画师的作品，3：随机获取一个关注中画师的作品，4：随机获取一个收藏中的作品
        RandomTags:             ['德丽莎','テレサ・アポカリプス']                    #RandomMode=1时查找的标签
        Template:               '本条数据来源于Pixiv，{MemberCD}秒后再来哦，今天剩余使用次数{TodayLeft}次，本消息将在{RevokeInterval}秒后撤回，私发需要给本bot发送任意消息开启临时会话哦~'
        MaxScreen:              60                                                  #根据标签搜索时,最多筛选N个作品,N个作品中不存在合格的涩图时,将返回NotFoundMsg
        MinBookmark:            1500                                                #最低收藏数，用于判断涩图是否合格(标签搜索时适用)
        MinBookRate:            0.05                                                #最低收藏率，收藏数/浏览数(标签搜索时适用)
    
    Lolicon:                                                                        #Lolicon图床https://api.lolicon.app/#/setu
        Enable:                 true                                                #是否启用
        Commands:               ['瑟图']                                              #命令，用法：#瑟图合法萝莉
        Template:               |                                                   #消息模版，值为空时将使用默认模版
                                本条数据来源于Lolicon，{MemberCD}秒后再来哦，今天剩余使用次数{TodayLeft}次，本消息将在{RevokeInterval}秒后撤回，私发需要给本bot发送任意消息开启临时会话哦~
                                PixivId：{PixivId}，标题：{IllustTitle}，画师：{UserName}，画师id：{UserId}，耗时：{CostSecond}s
                                标签：{Tags}，点击下方链接可以查看原图
                                {Urls}
    
    Lolisuki:                                                                       #Lolisuki图床https://lolisuki.cc，https://github.com/GardenHamster/LoliSuki
        Enable:                 true                                                #是否启用
        Commands:               ['setu']                                              #命令，用法：#瑟图合法萝莉
        Level:                  '0-6'                                               #Level范围，数字越大表示越涩，最小为0，最大为6，5-6为R18
        Template:               |                                                   #消息模版，值为空时将使用默认模版
                                本条数据来源于Lolisuki，{MemberCD}秒后再来哦，今天剩余使用次数{TodayLeft}次，本消息将在{RevokeInterval}秒后撤回，私发需要给本bot发送任意消息开启临时会话哦~
                                PixivId：{PixivId}，标题：{IllustTitle}，画师：{UserName}，画师id：{UserId}，Level：{Level}，分类：{Taste}，耗时：{CostSecond}s
                                标签：{Tags}，点击下方链接可以查看原图
                                {Urls}

Saucenao:                                                                           #Saucenao以图搜图，查找原图功能
    Enable:                     true                                                #是否启用
    Commands:                   ['原图','搜图']                                      #命令，用法：#原图 或 #原图+图片
    NotFoundMsg:                |                                                   #找不到相应色图时返回的消息
                                找不到相似的图，请换一张图片重试。
                                tips：如果通过截图获取搜索图片时，请只截取包含图片的部分，多余的色块只会影响搜索结果
    ProcessingMsg:              '正在通过saucenao尝试搜索原图...'                   #开始查找前返回的消息
    Template:                   '共找到 {MatchCount} 条匹配信息，相似度：{Similarity}%，来源：{SourceType}，今天剩余使用次数{TodayLeft}次，本消息将在{RevokeInterval}秒后撤回，CD{MemberCD}秒'
    MemberCD:                   30                                                  #独立CD(秒)，单个群员使用命令后需要等待的CD
    MaxDaily:                   0                                                   #每人每日最大使用次数，0表示无限制
    MaxReceive:                 10                                                  #每次最多接收并查询多少张图片，0表示无限制
    MinSimilarity:              60.00                                               #最低相似度(百分比)
    PullOrigin:                 true                                                #尝试从源网站中获取原图
    SendPrivate:                true                                                #同时私聊发送结果
    RevokeInterval:             0                                                   #N秒后撤回，0表示不撤回
    RevokeSearched:             false                                               #是否撤回要查找的图片
    ContinueAscii2d:            2                                                   #Saucenao没有匹配结果时是否继续使用Ascii2d搜索，0：否，1：是，2：询问
    Ascii2dReadCount:           3                                                   #从Ascii2d的搜索结果中读取前N条，0表示无限制

Subscribe:                                                                          #订阅相关
    PixivUser:                                                                      #订阅P站用户
        Enable:                 true                                                #是否启用
        ScanMode:               2                                                   #1：从pixiv账号获取已关注用户的最新作品并推送到拥有订阅权限的群（耗时短），2：逐个扫描订阅命令所订阅的画师（可自定义）
        AddCommands:            ['订阅画师']                                          #订阅命令,需要管理员执行
        RmCommands:             ['退订画师']                                          #退订命令,需要管理员执行
        SyncCommands:           ['同步画师']                                          #同步命令,从p站账号中获取关注画师列表并添加到订阅中,需要管理员执行
        Template:               'pixiv画师[{UserName}]发布了新作品：'               #消息模版，值为空时将使用默认模版
        ScanInterval:           3600                                                #扫描间隔(秒)
        ShelfLife:              43200                                               #保质期(秒),超过保质期将不会推送,0表示永不过期
    PixivTag:                                                                       #订阅P站标签
        Enable:                 true                                                #是否启用
        AddCommands:            ['订阅标签']                                          #订阅命令,需要管理员执行
        RmCommands:             ['退订标签']                                          #退订命令,需要管理员执行
        Template:               'pixiv标签[{TagName}]出现了新作品：'                #消息模版，值为空时将使用默认模版
        ScanInterval:           1800                                                #扫描间隔(秒)
        ShelfLife:              86400                                               #保质期(秒),超过保质期将不会推送,0表示永不过期
        MinBookmark:            300                                                 #最低收藏数，用于判断涩图是否合格
        MinBookPerHour:         60                                                  #距离作品发布每小时至少新增收藏数量，用于判断涩图是否合格
        MaxScan:                300                                                 #最多扫描前N个作品
    Miyoushe:                                                                       #订阅米游社版主
        Enable:                 true                                                #是否启用
        AddCommands:            ['订阅版主']                                          #订阅命令,需要管理员执行
        RmCommands:             ['退订版主']                                          #退订命令,需要管理员执行
        Template:               |                                                   #消息模版，值为空时将使用默认模版
                                米游社[{UserName}]发布了新帖子，发布时间：{CreateTime}
                                {Title}
                                {Content}
                                {Urls}
        ScanInterval:           60                                                  #扫描间隔(秒)
        ShelfLife:              43200                                               #保质期(秒),超过保质期将不会推送,0表示永不过期

TimingSetu:
    Enable:                     true                                                #是否启用
    LocalPath:                  'C:\BotImg\localSetu'                               #本地图片文件夹路径，图片需要分类放在子目录下，Source为0时可用
    FromOneDir:                 false                                               #true：从一个随机目录读取涩图，false：从不同的随机目录读取涩图，Source为0时可用
    LocalTemplate:              '文件名：{FileName}，目录：{FilePath}，大小：{SizeMB}MB'   #本地涩图消息模版
    LolisukiLevel:              '0-3'                                               #Lolisuki的Level，Source为2时可用
    Timers:                                                                         #定时列表
        - Cron:                 '0 0 15 * * ?'                                      #cron表达式，可以百度cron格式，或者在线生成
          Name:                 '下午茶'                                            #定时器名称
          Groups:               [284196392]                                         #发送到群
          Source:               2                                                   #图源，0：本地，1：Lolicon，2：Lolisuki
          SendMerge:            false                                               #合并消息发送
          Tags:                 []                                                  #涩图标签，不填表示随机，Source为1和2时可用
          Quantity:             5                                                   #发送涩图数量，Source为1和2时取值范围为1~20
          AtAll:                false                                               #是否艾特全体
          TimingMsg:            '下午茶时间，来点{Tags}涩图，图片来源：{SourceName}'   #提示消息
          
PixivRanking:
    Enable:                     true                                                #是否启用
    ProcessingMsg:              '正在获取榜单信息...'                                 #开始查找前返回的消息
    Template:                   '{Date}{Ranking}内容如下'                        #消息模版
    SendPreview:                true
    SendDetail:                 false
    SendMerge:                  false
    GroupCD:                    300
    MaxShow:                    50
    IncludeR18:                 false
    IllustOnly:                 true
    CacheSeconds:               3600
    Daily:
        Commands:               ['日榜']
        MinRatingCount:         1000
        MinRatingRate:          0.15
    DailyAI:
        Commands:               ['AI日榜']
        MinRatingCount:         1000
        MinRatingRate:          0.1
    DailyMale:
        Commands:               ['LSP日榜']
        MinRatingCount:         1000
        MinRatingRate:          0.2
    Weekly:
        Commands:               ['周榜']
        MinRatingCount:         3000
        MinRatingRate:          0.15
    Monthly:
        Commands:               ['月榜']
        MinRatingCount:         5000
        MinRatingRate:          0.15
    Subscribe:
        - Groups:               [284196392]
          Content:              ['Daily','DailyAI','DailyMale']
          Cron:                 '0 30 10 * * ?'

        - Groups:               [284196392]
          Content:              ['Weekly']
          Cron:                 '0 31 10 ? * SAT'

        - Groups:               [284196392]
          Content:              ['Monthly']
          Cron:                 '0 32 10 28 * ?'