Enable:                          true                                           #是否启用
JoinCommands:                   ['加入游戏']										#加入游戏命令
EndCommands:                    ['结束游戏']										#结束游戏命令
Undercover:
    Enable:                     true                                            #是否启用
    CreateCommands:             ['谁是卧底','卧底']						        #创建游戏命令


