Enable:                          true                                           #是否启用
JoinCommands:                   ['加入游戏']										#加入游戏命令
StopCommands:                   ['结束游戏']										#结束游戏命令
Undercover:
    Enable:                     true                                            #是否启用
    CreateCommands:             ['谁是卧底','卧底']						        #创建游戏命令
    AddWordCommands:            ['添加词条','新增词条']                           #新增词条命令，需要私聊使用
    SendWordCommands:           ['我的词条']                                     #游戏中获取词条命令
    MaxSimilarity:              50                                              #与历史发言的最高相似度(%)
    MatchSeconds:               120                                             #等待玩家加入的时间(秒)
    PrepareSeconds:             10                                              #派发词条后进入发言环节前的准备时间(秒)
    SpeakingSeconds:            120                                             #每个玩家的发言时长(秒)
    VotingSeconds:              120                                             #投票环节时长(秒)
    MuteSeconds:                0                                               #失败方被禁言的时长(秒)
    RuleMsg:                    |
                                以下是游戏规则：
                                所有卧底出局时，平民获胜
                                所有平民出局或者仅剩1平民1卧底时，卧底获胜