Enable:                          true                                           #是否启用
JoinCommands:                   ['加入游戏']										#加入游戏命令
StopCommands:                   ['结束游戏']										#结束游戏命令
Undercover:
    Enable:                     true                                            #是否启用
    CreateCommands:             ['谁是卧底','卧底']						        #创建游戏命令
    AddWordCommands:            ['添加词条','新增词条']                           #新增词条命令，需要私聊使用
    SendWordCommands:           ['我的词条']                                     #游戏中获取词条命令
    MaxSimilarity:              50                                              #与历史发言的最高相似度(%)
    MatchSeconds:               120                                             #等待玩家加入的时间(秒)
    PrepareSeconds:             10                                              #派发词条后进入发言环节前的准备时间(秒)
    SpeakingSeconds:            120                                             #每个玩家的发言时长(秒)
    VotingSeconds:              120                                             #投票环节时长(秒)
    MuteSeconds:                0                                               #失败方被禁言的时长(秒)
    RuleMsg:                    |
                                以下是游戏规则：
                                平民：找出混在其中的所有的卧底和白板
                                卧底：隐藏自己的身份，直到所有平民出局，或者存活仅剩2人为止
                                白板：没有词条，需要根据其他玩家的描述猜测出其中一个词条
                                白板发言中允许包含其他玩家的词条，但是这也意味这你的身份将会暴露，其他玩家的发言中不允许包含自己的词条
                                所有卧底出局或者白板的发言中包含其他玩家的词条时，白板将会获胜
                                白板玩家不会出现在前两名发言玩家当中