Enable:                     true                                                #是否启用
Commands:                   ['菜单','帮助','功能','指令','命令','help']           #命令
Template:                   ''                                                  #菜单模版，可自行设定，值为空时将自动生成